// Generic product engine — processes any structured intake and returns a spec object.
// The /api/spec route generated by Forge calls this function.
export function runProductEngine(body: Record<string, unknown>): Record<string, unknown> {
  const input = String(body.input || body.idea || body.resume || body.location || body.job_description || '').trim()
  const type = inferEngineType(body)
  return {
    type,
    input: input.slice(0, 500),
    processed: true,
    summary: input
      ? `Processed ${type} request: ${input.slice(0, 120)}${input.length > 120 ? '...' : ''}`
      : `Empty ${type} request — no input provided`,
    fields: Object.keys(body).filter(k => k !== 'input'),
    timestamp: new Date().toISOString(),
  }
}

function inferEngineType(body: Record<string, unknown>): string {
  if (body.resume || body.job_description) return 'career'
  if (body.idea || body.concept) return 'product'
  if (body.location || body.address) return 'location'
  if (body.grant || body.obligation) return 'compliance'
  if (body.policy || body.board) return 'governance'
  return 'general'
}
